apiVersion: apps/v1

kind: Deployment

metadata:
  name: springboot-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: springboot-api

  template:
    metadata:
      labels:
        app: springboot-api

    spec:
      containers:
      - name: springboot-api

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}