apiVersion: v1

kind: Service

metadata:
  name: springboot-service

spec:

  selector:
    app: springboot-api

  ports:

  - port: {{ .Values.service.port }}

    targetPort: {{ .Values.service.targetPort }}

  type: {{ .Values.service.type }}